name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: Whist-Team/actions/setup-poetry@v2
        with:
          python-version: '3.10'

      - name: Lint sources with flake8
        run: poetry run flake8 notation --count --show-source --statistics

      - name: Lint sources with pylint
        run: poetry run pylint notation

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run bandit
        uses: tj-actions/bandit@v5
        with:
          targets: |
            notation
          options: "-r"
